env_name: highway  # [highway, highwayFast]
lanes_count: 4
vehicles_count: 40
duration: 40  # [s]
render_mode: null # [null, 'human', 'RGB']
save_evaluation_video: False
vehicles_density: 1
reward:
  collision_reward: -1    # The reward received when colliding with a vehicle.
  non_collision_reward: 0
  right_lane_reward: 0.1  # The reward received when driving on the right-most lanes, linearly mapped to zero for other lanes.
  high_speed_reward: 0.4  # The reward received when driving at full speed, linearly mapped to zero for lower speeds according to config["reward_speed_range"].
  lane_change_reward: -0.05   # The reward received at each lane change action.
  reward_speed_range:  # for highway's default vehicles, speed range is [-40, 30]
    min: 20
    max: 30
  normalize_reward: True
# offroad_terminal: False
obs:
  type: GI  # only GrayImg (GI) here, if using Kinematics type, use highway_KM.yaml
  shape:
    w: 84
    h: 84
  stack_size: 4
  remove_frame_axis: False
act:
  type: DMeta  #  [DMeta, Disc] DMeta: DiscreteMetaAction, Disc: DiscreteAction
  actions_per_axis: null  # If not None, act.type should be Disc and in [3,5,7,9]
  target_speeds: 20-30-3